version: '3'

services:
  traefik:
    image: traefik
    command: -c /traefik.toml --logLevel=DEBUG
    ports:
      - "8085:80"
      - "8086:8080"
    networks:
      - traefik
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  whoami1:
    image: emilevauge/whoami
    networks:
      - traefik
    labels:
      - "traefik.backend=whoami"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.yourdomain.com"

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID=your-client-id
      - CLIENT_SECRET=your-client-secret
      - SECRET=something-random
      - COOKIE_SECURE=false
      - DOMAIN=yourcompany.com
      - AUTH_HOST=auth.yourdomain.com
    networks:
      - traefik
    # When using an auth host, adding it here prompts traefik to generate certs
    labels:
      - traefik.enable=true
      - traefik.port=4181
      - traefik.backend=traefik-forward-auth
      - traefik.frontend.rule=Host:auth.yourdomain.com

networks:
  traefik:
